//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterLibrary.Models.DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIET_NHAP
    {
        public int SOHD { get; set; }
        public string TENSACH { get; set; }
        public string NXB { get; set; }
        public string TACGIA { get; set; }
        public Nullable<int> SL { get; set; }
        public Nullable<decimal> GIANHAP { get; set; }
        public Nullable<decimal> GIABAN { get; set; }
    
        public virtual NHAPKHO NHAPKHO { get; set; }
    }
}
