//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterLibrary.Models.DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class LUATTHUVIEN
    {
        public int MALUAT { get; set; }
        public Nullable<int> SONGAYMUON { get; set; }
        public Nullable<decimal> TIENTRASACHMUONMOTNGAY { get; set; }
    }
}
