//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterLibrary.Models.DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHAPKHO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHAPKHO()
        {
            this.CHITIET_NHAP = new HashSet<CHITIET_NHAP>();
        }
    
        public int SOHD { get; set; }
        public Nullable<int> MANV { get; set; }
        public System.DateTime NGNHAP { get; set; }
        public Nullable<decimal> TRIGIA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIET_NHAP> CHITIET_NHAP { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
    }
}
