//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterLibrary.Models.DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUTHU
    {
        public int MAPHIEUTHU { get; set; }
        public Nullable<int> MAKH { get; set; }
        public Nullable<int> MASACH { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public System.DateTime NGAYTHU { get; set; }
        public System.DateTime NGAYHETHAN { get; set; }
        public Nullable<decimal> TIENTREMOTNGAY { get; set; }
        public Nullable<int> SOLUONGHONG { get; set; }
        public Nullable<decimal> TIENPHATHONG { get; set; }
        public Nullable<decimal> TONGTIEN { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual SACH SACH { get; set; }
    }
}
