//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterLibrary.Models.DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class SACH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SACH()
        {
            this.CTHDs = new HashSet<CTHD>();
            this.GIOHANGs = new HashSet<GIOHANG>();
            this.PHIEUMUONs = new HashSet<PHIEUMUON>();
            this.PHIEUTHUs = new HashSet<PHIEUTHU>();
        }
    
        public int MASACH { get; set; }
        public string TENSACH { get; set; }
        public string TACGIA { get; set; }
        public Nullable<int> NAMXB { get; set; }
        public Nullable<decimal> GIA { get; set; }
        public string IMAGESOURCE { get; set; }
        public string THELOAI { get; set; }
        public string MOTA { get; set; }
        public Nullable<int> VITRITANG { get; set; }
        public Nullable<int> VITRIDAY { get; set; }
        public string NXB { get; set; }
        public Nullable<int> SL { get; set; }
        public Nullable<int> ISEXIST { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHD> CTHDs { get; set; }
        public virtual DAYKE DAYKE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GIOHANG> GIOHANGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUMUON> PHIEUMUONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUTHU> PHIEUTHUs { get; set; }
        public virtual TANG TANG { get; set; }
    }
}
