//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterLibrary.Models.DataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUCO
    {
        public int MASC { get; set; }
        public Nullable<int> MAKH { get; set; }
        public string TIEUDE { get; set; }
        public string MOTA { get; set; }
        public string IMG { get; set; }
        public Nullable<decimal> CHIPHI { get; set; }
        public System.DateTime THOIGIANBAOCAO { get; set; }
        public Nullable<int> MALSC { get; set; }
        public string MATTSC { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual LOAISUCO LOAISUCO { get; set; }
        public virtual TRANGTHAISC TRANGTHAISC { get; set; }
    }
}
